# Generated by Django 5.0.6 on 2024-05-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('favouritecities', models.CharField(max_length=40)),
                ('visitedCities', models.CharField(max_length=40)),
            ],
        ),
    ]
