# Generated by Django 5.0.6 on 2024-05-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_traveller_confpassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller',
            name='favouritecities',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='visitedCities',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
