# Generated by Django 5.0.6 on 2024-05-14 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('attractions', models.TextField(default=None, verbose_name='attractions of the city ')),
                ('cityImages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.images')),
            ],
        ),
    ]
