# Generated by Django 5.0.6 on 2024-05-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_remove_cities_cityimages_delete_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='cityImages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.images'),
        ),
    ]
