# Generated by Django 5.0.6 on 2024-05-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_images_cities_cityimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='cityImages',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
