# Generated by Django 5.0.6 on 2024-05-14 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='cityImages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.images'),
        ),
    ]
