# Generated by Django 5.0.6 on 2024-05-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_cities_cityimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='cityImages',
        ),
    ]
